/* 1. CREATE SCHEMA
	STEP 1: Click create a new schema.
    STEP 2: Maglagay ng name 
    STEP 3: Click apply.*/  

/* 2. CREATE TABLE.
	STEP 1: SELECT DATABASE 
    STEP 2: RIGHT CLICK THE TABLE
    STEP 3: SELECT CREATE A TABLE*/ 
    
/* 3. INSERTING DATA 
	STEP 1: RIGHT CLICK TABLES. 
    STEP 2: SELECT ROWS.
    STEP 3: INPUT YOUR DATA IN ROWS.
	STEP 4. APPLY.*/  

/* 4. UPDATING DATA 
	STEP 1: RIGHT CLICK TABLES.
    STEP 2: SELECT ROWS.
    STEP 3: EDIT THE ROWS YOU WANT.
    STEP 4. APPLY.*/ 

/* 5. DELETING DATA
	STEP 1: RIGHT CLICK TABLES.
    STEP 2: SELECT AND RIGHT CLICK ROWS.
    STEP 3: DELETE ROW.
    STEP 4: APPLY.*/ 
/* 6. TRUNCHATE TABLE
	STEP 1: RIGHT CLICK TABLENAME.
    STEP 2: SELECT TRUNCATE TABLE*/
/* 7. DELETE TABLE
	STEP 1: RIGHT CLICK TABLENAME.
    STEP 2: SELECT DROP TABLE*/
/* 8. DROP SCHEMA OR DATABASE
	STEP 1: RIGHT CLICK DATABASE_NAME.
    STEP 2: SELECT DROP SCHEMA*/
