-- CREATING DATABASE  
-- create database database_name;
create database dbSchool; 

-- CREATING A TABLE 
-- create table table_name)variable datatype); 
-- or create table table_name (variable datatype constraint);  

-- Primary Key 
-- The Unique data tha is used to indetify an individual set of data. 
-- This is often auto generated by the progrma. 

-- Type of Contraints
-- NOT NULL - Will not accept empty values.
-- UNIQUE - Will not accept duplicate values. 
-- 3. PRIMARY KEY - Will not accept empty and duplicate values. 
-- 4. AUTO_INCREMENT - This keyword is used so that your primary key 
-- would be automatically generated for you.
-- Only works with numerical data. 

-- Most Common SQL Data Type. 

-- 1. Numeric Data
-- 1. INTEGER / INT - Stores numeric values from - 2147463648 to 2147483647. 
-- 2. DOUBLE - Stores numeric values with decimals with lower floating point than float. 
-- 3. FLOAT - Sotres numeric with decimals with a high floating point. 
-- 4. BOOL - Store TRUE = 1 or FALSE = 0. 

-- 2. Text Data. 
-- 1. VARCHAR - Set of characters with a width or size up to 8000 charcters. 
-- 2. TEXT - Set of characters with the size of 2GB text data. 
-- 3. TIME DATA - also text data.
	-- DATA - Stores Date in the format YYYY-MM--DD.
    -- TIME - Stores Time in the format hh:mm:ss. 
    -- DATETIME - Stores Date and time in the format YYYY-MM-DD hh:mm:ss.alter
-- 4. MISCELLANEOUS DATA.
	-- BLOB - Stores large binary data. 
    
create table tblStudent( 
StudentID int primary key auto_increment, 
FirstName varchar(16) not null,
LastName varchar(16) not null,
PhoneNumber varchar(11),
Scholarship bool not null, 
DateEnrolled date not null
); 
 -- CREATING DATABASE  
-- create database database_name;
create database dbSchool; 

-- CREATING A TABLE 
-- create table table_name)variable datatype); 
-- or create table table_name (variable datatype constraint);  

-- Primary Key 
-- The Unique data tha is used to indetify an individual set of data. 
-- This is often auto generated by the progrma. 

-- Type of Contraints
-- NOT NULL - Will not accept empty values.
-- UNIQUE - Will not accept duplicate values. 
-- 3. PRIMARY KEY - Will not accept empty and duplicate values. 
-- 4. AUTO_INCREMENT - This keyword is used so that your primary key 
-- would be automatically generated for you.
-- Only works with numerical data. 

-- Most Common SQL Data Type. 

-- 1. Numeric Data
-- 1. INTEGER / INT - Stores numeric values from - 2147463648 to 2147483647. 
-- 2. DOUBLE - Stores numeric values with decimals with lower floating point than float. 
-- 3. FLOAT - Sotres numeric with decimals with a high floating point. 
-- 4. BOOL - Store TRUE = 1 or FALSE = 0. 

-- 2. Text Data. 
-- 1. VARCHAR - Set of characters with a width or size up to 8000 charcters. 
-- 2. TEXT - Set of characters with the size of 2GB text data. 
-- 3. TIME DATA - also text data.
	-- DATA - Stores Date in the format YYYY-MM--DD.
    -- TIME - Stores Time in the format hh:mm:ss. 
    -- DATETIME - Stores Date and time in the format YYYY-MM-DD hh:mm:ss.alter
-- 4. MISCELLANEOUS DATA.
	-- BLOB - Stores large binary data. 
    
create table tblStudent( 
StudentID int primary key auto_increment, 
FirstName varchar(16) not null,
LastName varchar(16) not null,
PhoneNumber varchar(11),
Scholarship bool not null, 
DateEnrolled date not null
); 
alter table tblstudent
add StudentID int primary key auto_increment;



/* INSERTING DATA 
- INSERT INTO table_name(p1,p2..) VALUES (v1,v2..);*/ 

INSERT INTO tblstudent 
( -- Jindi na kasama ang StudentID kasi naka auto increment naman na
Firstname,
LastName, 
PhoneNumber,
Scholarship,
DateEnrolled) values 
("SDPT", "Solutions", "09123456789", FALSE, "2025-07-13"),
("SDPT", "Problems", "09123456798", FALSE, "2025-07-13");
select * from tblstudent;
